const video = document.querySelector('.player')
const canvas = document.querySelector('.photo')
const strip = document.querySelector('.strip')
const snap = document.querySelector('.snap')
const ctx = canvas.getContext('2d')